# **NumPy**

 ***NumPy is a python library used for working with arrays.***

In [1]:
#import the library
import numpy as np

In [2]:
#create a list
a=[2,5.6,"python",True]
a

[2, 5.6, 'python', True]

In [6]:
#create a numpy array
b=np.array(a)
b

array(['2', '5.6', 'python', 'True'], dtype='<U32')

In [7]:
type(b)

numpy.ndarray

In [8]:
#assign a new value 
b[3]=1
b

array(['2', '5.6', 'python', '1'], dtype='<U32')

In [9]:
b.dtype

dtype('<U32')

In [13]:
#create two new array
new = np.array(["John","Rick","Jack"])
latest = np.array([5.6,8.9,10.8])
print(new)
print(latest)

['John' 'Rick' 'Jack']
[ 5.6  8.9 10.8]


In [14]:
print(new.dtype)
print(latest.dtype)

<U4
float64


## Slicing

In [15]:
stack =  np.arange(0,101)
stack

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [16]:
queue =  np.arange(0,50,3)
queue

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [17]:
print(stack[0:9])
print(queue[:-10])
print(queue[::-1]) # print the array reversely

[0 1 2 3 4 5 6 7 8]
[ 0  3  6  9 12 15 18]
[48 45 42 39 36 33 30 27 24 21 18 15 12  9  6  3  0]


In [19]:
# Get the size of numpy array
print("Size of the stack array :", stack.size)
print("Size of the queue array :", queue.size)

Size of the stack array : 101
Size of the queue array : 17


In [22]:
# find the max,min,mean,median of queue array
print("Minimum value presents in queue array :", queue.min())
print("Maximum value presents in queue array :", queue.max())
print("Mean of the values present in queue array :", queue.mean())
print("Sum of the values present in queue array :", queue.sum())

Minimum value presents in queue array : 0
Maximum value presents in queue array : 48
Mean of the values present in queue array : 24.0
Sum of the values present in queue array : 408


## Array Addition

In [23]:
p=np.array([9,8,5])
q=np.array([23,15,90])
z=p+q
print(z)

[32 23 95]


## Product of Two Numpy Arrays

In [24]:
r= p*q
r

array([207, 120, 450])

## Dot Product

In [25]:
g=np.dot(p,q)
g

777

## Mathematical Functions

In [26]:
# Create the numpy array in radians
x = np.array([0, np.pi/2 , np.pi])

In [27]:
# Calculate the sin of each elements
y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

## linspace

In [28]:
m = np.linspace(0,10,3)
m

array([ 0.,  5., 10.])

## Matrix

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
y=np.ones((2,3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
y*4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [36]:
#identity matrix
np.eye(4)  # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
#find the matrix shape & size
print("shape of the matrix :",y.shape)
print("size of the matrix :",y.size)

shape of the matrix : (2, 3)
size of the matrix : 6


In [40]:
#matrix with random no.
np.random.randint(1,50,(4,4)) # 4x4 matrix with random numbers between 1 & 50

array([[32,  4, 17,  6],
       [34, 28, 32, 47],
       [17,  5, 49, 11],
       [33, 35, 40, 22]])

In [43]:
# Access the element on the second row and third column
y[1, 2]

1.0

In [50]:
#array shape change
arr = np.array(([2,3,4],[56,7,90],[54,32,24],[6,7,89]))
print(arr)
print("previous shape :",arr.shape)
new_arr = arr.reshape(2,6)
print("new matrix:\n", new_arr)
print("new shape:", new_arr.shape)

[[ 2  3  4]
 [56  7 90]
 [54 32 24]
 [ 6  7 89]]
previous shape : (4, 3)
new matrix:
 [[ 2  3  4 56  7 90]
 [54 32 24  6  7 89]]
new shape: (2, 6)


In [51]:
#transpose of a matrix
transpose_matrix = np.transpose(new_arr)
transpose_matrix

array([[ 2, 54],
       [ 3, 32],
       [ 4, 24],
       [56,  6],
       [ 7,  7],
       [90, 89]])

In [52]:
arr[2] 

array([54, 32, 24])

In [53]:
arr[2,1]

32

In [54]:
arr[1:,1:]

array([[ 7, 90],
       [32, 24],
       [ 7, 89]])

In [55]:
arr[:2,:2]

array([[ 2,  3],
       [56,  7]])

In [57]:
arr[:3,2:]

array([[ 4],
       [90],
       [24]])

In [58]:
arr[:2]

array([[ 2,  3,  4],
       [56,  7, 90]])

In [62]:
#matrix Multiplication
H=np.random.randint(1,100,(4,4))
I=np.random.randint(1,50,(4,4))
J=H*(I**2)#multiply H matrix with square of I matrix
J

array([[ 16940,   2880, 102366,   2156],
       [106575,  57660,  38592,  24548],
       [ 32256,  60648,    396,  38400],
       [  2325, 158752,   3312,   7056]])